--- #YAML:1.0
name:               Squatting-On-HTTP-Engine
version:            0.04
abstract:           run Squatting apps on top of HTTP::Engine
author:
    - John BEPPU <beppu@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Engine:  0.1.4
    Squatting:     0.52
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
no_index:
    directory:
        - eg
        - t
